--first remove foreign key constraints from departments
ALTER TABLE IF EXISTS departments
    DROP COLUMN manager;

--DROP the tables and constraints
DROP TABLE IF EXISTS employee_project;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS employeee;
DROP TABLE IF EXISTS department;

--create the project table, it depends on no other tables
CREATE TABLE project (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_name TEXT NOT NULL,
    budget NUMERIC DEFAULT 0,
    start_date DATE
);

--create the department table without the foreign key
CREATE TABLE department (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dept_name TEXT NOT NULL
);

--create the employee table
--make foreign keys immediately as the two dependencies as exist
CREATE TABLE employee (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    emp_name TEXT NOT NULL,
    phone TEXT,
    title TEXT,
    salary NUMERIC,
    department INTEGER REFERENCES department(id) 
);

--now make the manager relationship between department and
--employee possible, alter the table and add the constraint
ALTER TABLE department
    ADD COLUMN manager INTEGER REFERENCES employee(id);

--create the employee_project table
--has references to both emp's and prjcts
--primary key is two columns
CREATE TABLE employee_project (
    emp_id INTEGER REFERENCES employee(id),
    project_id INTEGER REFERENCES project(id),
    start_date DATE,
    end_date DATE,
    PRIMARY KEY (emp_id, project_id)
);
--PRIMARY KEY defined after columns are all defined.